# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 11:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('app01', '0002_auto_20171019_0654'),
    ]

    operations = [
        migrations.AddField(
            model_name='usergroup',
            name='test',
            field=models.CharField(blank=True, max_length=32, null=True, verbose_name='测试'),
        ),
    ]
